---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.cumulonimbus
  resources:
  - scalepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cumulonimbus
  resources:
  - scalepods/finalizers
  verbs:
  - update
- apiGroups:
  - app.cumulonimbus
  resources:
  - scalepods/status
  verbs:
  - get
  - patch
  - update
