apiVersion: app.cumulonimbus/v1alpha1
kind: Scalepod
metadata:
  labels:
    app.kubernetes.io/name: scalepod
    app.kubernetes.io/instance: scalepod-sample
    app.kubernetes.io/part-of: scalepod
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scalepod
  name: scalepod-sample
spec:
  # TODO(user): Add fields here
